### PR TITLE
Add Maven Central publishing to build.gradle

### PR DESCRIPTION
**Pull request by MathNerd28**

### CODE REVIEW

**Comment by MathNerd28** [comment]
Javadoc generation is currently failing; this is fixed on branch command-framework, please ignore

**Comment by mmarchetti** [comment]
I don't have enough Maven experience to review this PR. I will note that if you have a fix for the Javadoc issue in a clean commit on another branch, you can bring it over with `git cherry-pick <commit>` while on this branch. Both branches will be mergeable even though they both have the fix, because it is the same commit.

**Comment by MathNerd28** [comment]
Just cherry-picked the javadoc fix and merged master into this branch. As for Maven experience, I don't know if any of us do, but the generated pom.xml is compliant with almost all Maven Central requirements. The one sticking point is that I can't get Gradle to include the custom dependency repositories.

**Comment by MathNerd28** [comment]
Fix exists in command-framework. Cannot cherry-pick because it modifies files that don't exist yet.

**Review by mmarchetti — APPROVED** [review]

**Pull request merged**
